name: Example usage of GitHub-Action-Ahk2Exe and softprops/action-gh-release

on: [push]

jobs:
  Example2:
    name: Example2
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: MainScript.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: example.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
